<!-- Google tag (gtag.js)--> 
<script async src="https://www.googletagmanager.com/gtag/js?id=G-S1L73VGCG5"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-S1L73VGCG5');
</script>

# Comandos Básicos no Jmol (ou...o que se pode fazer com modelos de biomoléculas)

|       O *Jmol* possui uma infinidade de comandos para visualização e estudo de modelos moleculares. Grande parte desses comandos é acessada pelo *Menu* principal do *Jmol*, ou por clique do botão direito do mouse no ecrã principal do programa ou do *applet JSmol* na internete.
|       Entretanto, a *escriptagem* permite pelo *Console*, tanto do programa instalado como do *applet* a execução de um conjunto bem maior de ações, além de permitir elencar ações consecutivas gerando visualizações específicas, cálculos e animações, e mesmo *programação.* Nesse último caso, pela linguagem *Jmol scripting*. Esses comandos e a linguagem programação estão explicitados no site de seus desenvolvedores, [Jmol - Documentação & Escriptagem](https://chemapps.stolaf.edu/jmol/docs/?ver=14.32#plot){target="_blank"}. O conteúdo deste capítulo visa sumarizar os principais comandos para a visualização, estudo, importação e exportação, cálculos e animações dos modelos.

## Mudando a linguagem da interface & diretório de arquivos

### Linguagem

### Diretório

## Obtendo modelos moleculares

### Bancos de dados moleculares

## Operações de mouse e teclado

## Salvando os modelos

## Exportando modelos

### Copiando para o clipboard

## Calculando distâncias e ângulos

## Alterando as representações 

### Visualizando ou não o hidrogênio

## Selecionando cores

## Selecionando partes do modelo

## Etiquetando átomos ou partes do modelo

## Ampliação dos modelos (Zoom)

## Criando e lendo scripts

## Animações nos modelos

### ZoomTo

### Move

### MoveTo

### Navigate

### Delay

## Trabalhando com programação






