---
title: "SISMA - Visualizando a Dinâmica do Metabolismo "
author: 
# hidedate: TRUE
date:  
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
---

<font size="4">

|       **Sisma** é um programa elaborado com a proposta inicial de gerar uma imagem dinâmica de transformações ocorridas entre reagentes e produtos de uma rede, e pela simples inserção de compostos (*object*) interligados por setas (*path*).

|       O programa escrito em Java permite visualizar dinamicamente e avaliar a transformação de reagentes e produtos de uma reação, fluxo metabólico, ou mapas complexos. Trata-se de um  acrônimo para *Sistema de Mapas Autocatalíticos*, e permite uma simulação visual e quantitativa num mapa bidimensional, de mudanças que ocorrem em cadeia ou rede, pela percepção de variações de cores e matizes nos objetos envolvidos em cada tranformação a partir de equação introduzida pelo usuário.

|       Para o estudo dessas relações, o programa permite inserção de objetos, vias, figuras e anotações no mapa, armazenamento e leitura de mapas, simulação em tempo real por gráfico de pontos e linhas para cada objeto simultâneas às que ocorrem no próprio mapa, pausa, interrupção, retrocesso e avanço da visualização a qualquer rmomento da simulação, geração automática e exportação de planilha contendo os valores numéricos de cada objeto transformado em cada instante, e impressão instantânea do mapa no ponto de uma transformação desejada. Dessa forma, o programa torna dinâmica a visualização de forças e de fluxos que são apresentados de forma estática em representações bidimensionais de mesma natureza. 

## Download ##

|       O arquivo comprimido contendo o programa pode ser obtido neste [link](.\Sisma.zip)

## Dica rápida de uso ##
|       Para utilizar o **Sisma** baixe o arquivo do link acima e descompacte-o no seu PC. Não requer instalação, apenas *JAVA*. Para executá-lo, vá para a pasta "dist" e clique no arquivo de Java ("Sisma_Realese_1.jar").

## Tutorial ##

|       Para começar a inserir *objetos* e *caminhos* no **Sisma** pode-se seguir esse [tutorial](.\sisma.tut.pdf). Segue também um exemplo de *mapa autocatalítico* rodado no *Sisma* para a [Glicólise](.\glicolise.sis).



</font>


